### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [mpconk/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, looks good. Your code was well organized and easy to understand. It was very clear you really absorbed the material: usage of alt attributes, strong tags, inheritance to set font. As projects grow there will be a greater need for div usage and you will start to figure out that a div with no selector will be fairly useless. It is always easier to reach inside a container than to reach out of it. Good job on this project, you are ready for the next lessons.

**Comment by mpconk** [comment]
Thank you
